services:
  plusflix:
    build: ./docker/php
    container_name: plusflix_app
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./docker/php:/app/docker/php #okropny volume ale cóż
      - ../../SQLite:/app/sqlite_source:ro   
    ports:
      - "8080:8000"
    entrypoint: ["/app/docker/php/entrypoint.sh"]

