services:
  plusflix:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: plusflix_app
    working_dir: /app
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/templates:/app/templates:cached
      - ./backend/public:/app/public:cached
      - ./backend/.env:/app/.env
      - ../../SQLite:/app/sqlite_source:ro
    ports:
      - "8080:8000"
    entrypoint: ["entrypoint.sh"]
