services:
  plusflix:
    build: ./docker/php
    container_name: plusflix_app
    working_dir: /app
    volumes:
      - ./backend:/app
      - ../../SQLite:/app/sqlite_source:ro   
    ports:
      - "8080:8000"
    entrypoint: ["entrypoint.sh"]

